version: '3.7'

services:
  postgis:
    restart: always
    build: ./postgis
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgeo
      - TZ=GMT+3
      - PGTZ=GMP+3
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  jupyt:
    build: ./jupyp
    ports:
      - 8880:8880
    environment:
      - JUPYTER_TOKEN=secret
    volumes:
      - ./notebooks:/home/appuser/works